# Generated by Django 4.2.3 on 2023-09-13 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
        ('users', '0002_remove_user_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifiedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='space.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='notified_locations',
            field=models.ManyToManyField(through='users.NotifiedLocation', to='space.space'),
        ),
    ]
