# Generated by Django 4.2.3 on 2023-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_event_image_directory'),
        ('users', '0003_notifiedlocation_user_notified_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(to='event.tags'),
        ),
    ]
