# Generated by Django 4.2.3 on 2023-10-10 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('check-in', 'Check In'), ('check-out', 'Check Out')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ContributionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('contribution', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('volunteer_registration_enabled', models.BooleanField(default=True)),
                ('current_num_of_participants', models.PositiveIntegerField(default=0)),
                ('current_num_of_volunteers', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('On Going', 'On Going'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=10)),
                ('event_image_directory', models.TextField(default=None, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now=True)),
                ('has_left_forum', models.BooleanField(default=False)),
                ('rewarded', models.BooleanField(default=False)),
                ('submitted_review', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='GoalKind',
            fields=[
                ('kind', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(auto_now=True)),
                ('transaction_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AttendableEventParticipation',
            fields=[
                ('eventparticipation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.eventparticipation')),
                ('is_currently_attending', models.BooleanField(default=False)),
                ('overall_duration_in_seconds', models.FloatField(default=0)),
                ('has_attended', models.BooleanField(default=False)),
                ('has_violated_geofencing_rule', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('event.eventparticipation',),
        ),
        migrations.CreateModel(
            name='ContributionParticipation',
            fields=[
                ('eventparticipation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.eventparticipation')),
                ('total_contribution', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('event.eventparticipation',),
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.event')),
                ('participation_registration_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('event.event',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.event')),
                ('goal', models.FloatField()),
                ('progress', models.FloatField(default=0)),
                ('measurement_unit', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('event.event',),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='event_tags_name_541e54_idx')],
            },
        ),
    ]
