# Generated by Django 4.2.3 on 2023-10-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='average_event_rating',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='average_sentiment_score',
            field=models.FloatField(default=None),
        ),
    ]
