# Generated by Django 4.2.3 on 2023-10-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendableeventparticipation',
            name='has_attended',
            field=models.BooleanField(default=False),
        ),
    ]
