# Generated by Django 4.2.3 on 2023-10-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_current_num_of_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalKind',
            fields=[
                ('kind', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
    ]
