# Generated by Django 4.2.3 on 2023-10-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_contributionactivity_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='submitted_review',
            field=models.BooleanField(default=False),
        ),
    ]
