# Generated by Django 4.2.3 on 2023-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventparticipation_submitted_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='average_event_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='average_participant_attendance_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='average_sentiment_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_durations_counted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_ratings_submitted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_sentiments_submitted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
