# Generated by Django 4.2.3 on 2023-09-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_status_delete_eventstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image_directory',
            field=models.TextField(default=None, null=True),
        ),
    ]
