# Generated by Django 4.2.3 on 2023-10-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_average_forum_post_sentiment_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='average_forum_post_sentiment_score',
        ),
        migrations.RemoveField(
            model_name='event',
            name='number_of_post_sentiment_computed',
        ),
    ]
