# Generated by Django 4.2.3 on 2023-10-07 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_goalkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal_kind',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='event.goalkind'),
        ),
    ]
