# Generated by Django 4.2.3 on 2023-09-18 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0005_event_event_image_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('event_rating', models.SmallIntegerField(null=True)),
                ('event_review', models.TextField(null=True)),
                ('does_attend', models.BooleanField(default=False)),
                ('participation_type', models.CharField(choices=[('participant', 'Participant'), ('volunteer', 'Volunteer')])),
            ],
        ),
        migrations.AddIndex(
            model_name='tags',
            index=models.Index(fields=['name'], name='event_tags_name_541e54_idx'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventparticipation',
            index=models.Index(fields=['event', 'participant'], name='event_event_event_i_625d8f_idx'),
        ),
    ]
