# Generated by Django 4.2.3 on 2023-10-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_average_event_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='average_participant_attendance_duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='number_of_durations_counted',
        ),
        migrations.AddField(
            model_name='initiative',
            name='average_participant_attendance_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='initiative',
            name='number_of_durations_counted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
