# Generated by Django 4.2.3 on 2023-09-19 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_event_image_directory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddIndex(
            model_name='tags',
            index=models.Index(fields=['name'], name='event_tags_name_541e54_idx'),
        ),
    ]
