# Generated by Django 4.2.3 on 2023-10-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_average_forum_post_sentiment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='first_participation_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
