# Generated by Django 4.2.3 on 2023-09-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventcategory_tags_event_tags_name_541e54_idx'),
        ('event', '0006_eventparticipation_tags_event_tags_name_541e54_idx_and_more'),
    ]

    operations = [
    ]
