# Generated by Django 4.2.3 on 2023-10-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventparticipation_first_participation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='number_of_attending_participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
