# Generated by Django 4.2.3 on 2023-09-29 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('event', '0007_merge_20230929_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVolunteerParticipation',
            fields=[
                ('eventparticipation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.eventparticipation')),
                ('granted_manager_access', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('event.eventparticipation',),
        ),
        migrations.RenameField(
            model_name='eventparticipation',
            old_name='registration_date',
            new_name='registration_time',
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='does_attend',
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='participation_type',
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='check_in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='check_out_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
