# Generated by Django 4.2.3 on 2023-09-30 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0008_eventvolunteerparticipation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipation',
            name='event_rating',
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='event_review',
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='has_left_forum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ProjectContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_rating', models.SmallIntegerField(null=True)),
                ('event_review', models.TextField(null=True)),
                ('contribution_time', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.project')),
            ],
        ),
    ]
