# Generated by Django 4.2.3 on 2023-10-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_eventparticipation_event_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontribution',
            name='event_rating',
        ),
        migrations.RemoveField(
            model_name='projectcontribution',
            name='event_review',
        ),
        migrations.AddField(
            model_name='projectcontribution',
            name='has_left_forum',
            field=models.BooleanField(default=False),
        ),
    ]
