# Generated by Django 4.2.3 on 2023-10-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_rating', models.SmallIntegerField()),
                ('event_comment', models.TextField(null=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventparticipation')),
            ],
        ),
    ]
