# Generated by Django 4.2.3 on 2023-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_delete_contributionreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationreview',
            name='sentiment_score',
            field=models.FloatField(default=0),
        ),
    ]
