# Generated by Django 4.2.3 on 2023-10-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='sentiment_score',
            field=models.FloatField(default=0),
        ),
    ]
