# Generated by Django 4.2.3 on 2023-10-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_forumpost_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='average_sentiment_score',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='number_of_post_sentiment_calculated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
