# Generated by Django 4.2.3 on 2023-10-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_forum_average_sentiment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='top_words',
            field=models.JSONField(default={}),
        ),
    ]
