# Generated by Django 4.2.3 on 2023-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_forum_top_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='top_words',
            field=models.JSONField(default=dict),
        ),
    ]
