# Generated by Django 4.2.3 on 2023-10-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_alter_forum_top_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='author_role',
            field=models.CharField(default='participant'),
        ),
    ]
